eureka:
  instance:
    hostname: localhost
  client:
    #    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/member/**
        - id: member-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/member/**
        - id: branch-auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/auth/branch/**
        - id: branch-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/branch/**

management:
  tracing:
    sampling:
      probability: 1.0
